@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Dec 29 12:33:32 -0300 2020
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim testbench_veri_time_impl -key {Post-Implementation:sim_1:Timing:testbench_veri} -tclbatch testbench_veri.tcl -view C:/Users/luciana/Documents/ICTP/20celulas_simula_red_alta_c_testbemch_verilog/project_1/testbench_veri_time_impl.wcfg -log simulate.log"
call xsim  testbench_veri_time_impl -key {Post-Implementation:sim_1:Timing:testbench_veri} -tclbatch testbench_veri.tcl -view C:/Users/luciana/Documents/ICTP/20celulas_simula_red_alta_c_testbemch_verilog/project_1/testbench_veri_time_impl.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
